name: Run Gradle to build JAR releases
on:
  release:
    types: [created, edited]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew buildFatJar
    
    - name: Upload Jar to release
      uses: actions/upload-artifact@v2
      with: 
        name: Release
        path: ./app/build/libs/autelineATM.jar

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./app/build/libs/autelineATM.jar
